[build-system]
requires = ["setuptools >= 61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = [
    'umndet',
]

[project]
requires-python = ">= 3.11"
version = "0.1.4"
name = "umndet"
description = 'Ground code for the IMPRESS/EXACT missions'
readme = 'readme.md'
dependencies = [
    # We have none for the "core"
]

[project.optional-dependencies]
all = [
    "numpy",
    "matplotlib"
]

[project.scripts]
# Decoder helper scripts
decode-impress-health = "umndet.ground.json_decoders:decode_health"
decode-impress-science = "umndet.ground.json_decoders:decode_impress_sci"
decode-x123-science = "umndet.ground.json_decoders:decode_x123_sci"
decode-exact-science = "umndet.ground.json_decoders:decode_exact_sci"
